# Generated by Django 5.2.1 on 2025-07-21 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50, verbose_name='Nombre de la tarea')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de finalizacion')),
                ('finished', models.BooleanField(default=False, verbose_name='Terminada')),
                ('labor_cost', models.IntegerField(verbose_name='Costo de mano de obra')),
                ('requirements', models.ManyToManyField(blank=True, related_name='tasks', to='inventory.inventory')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TasksRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_material_cost', models.IntegerField(verbose_name='Costo total de todo el material de los requerimientos')),
                ('fk_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='Inventario')),
                ('fk_tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_plan.tasks', verbose_name='Tareas')),
            ],
            options={
                'db_table': 'work_plan_tasks_requirements',
            },
        ),
        migrations.CreateModel(
            name='Work_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50, verbose_name='Nombre del plan de trabajo')),
                ('status', models.BooleanField(default=False)),
                ('fk_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.component', verbose_name='Componente')),
            ],
            options={
                'db_table': 'work_plan',
            },
        ),
        migrations.AddField(
            model_name='tasks',
            name='fk_work_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_plan.work_plan', verbose_name='Plan de Trabajo'),
        ),
    ]
