# Generated by Django 5.2.1 on 2025-07-21 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(verbose_name='Grupo')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=20, verbose_name='Sistema')),
                ('acronym', models.CharField(max_length=20, verbose_name='Siglas')),
                ('condition', models.IntegerField(choices=[(0, 'Disponible'), (1, 'Indisponible'), (2, 'Descartada')], default=0, verbose_name='Condición')),
                ('status', models.FloatField(blank=True, null=True, verbose_name='Horas de vuelo')),
                ('utility_life', models.FloatField(blank=True, null=True, verbose_name='Vida útil')),
                ('fk_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.group')),
            ],
            options={
                'db_table': 'system',
            },
        ),
    ]
