# Generated by Django 5.2.1 on 2025-07-21 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=50, verbose_name='Componente')),
                ('category', models.IntegerField(choices=[(0, 'Mayor nivel'), (1, 'Menor nivel')], default=0, verbose_name='Nivel')),
                ('status', models.FloatField(verbose_name='Horas de vuelo')),
                ('utility_life', models.FloatField(verbose_name='Vida útil')),
                ('fk_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.system', verbose_name='Sistema')),
            ],
            options={
                'db_table': 'component',
            },
        ),
        migrations.CreateModel(
            name='ComponentObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones')),
                ('type', models.IntegerField(choices=[(0, 'Programado'), (1, 'No Programado')], default=0, verbose_name='Nivel')),
                ('fk_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='component.component', verbose_name='Componente')),
            ],
            options={
                'db_table': 'component_observation',
            },
        ),
    ]
