# Generated by Django 5.2.1 on 2025-07-21 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component', '0001_initial'),
        ('work_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentobservation',
            name='fk_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_plan.tasks', verbose_name='Tareas'),
        ),
    ]
