# Generated by Django 5.2.1 on 2025-07-21 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.IntegerField(choices=[(0, 'Otra_Locación'), (1, 'Proveedor2'), (2, 'Proveedor3')], default=0, verbose_name='Proveedor')),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255, verbose_name='Nombre del material')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad disponible en inventario')),
                ('part_number', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
                ('nomenclature', models.CharField(max_length=100)),
                ('cage', models.CharField(blank=True, max_length=50, null=True)),
                ('errc', models.CharField(blank=True, max_length=50, null=True)),
                ('ui', models.CharField(blank=True, max_length=50, null=True)),
                ('ser', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_inv_date', models.DateField()),
                ('fk_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.component', verbose_name='Componente')),
                ('fk_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Locación')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
