# Generated by Django 5.2.1 on 2025-07-21 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Nivel de mantenimiento')),
                ('hours', models.IntegerField(verbose_name='Horas que corresponde el nivel')),
            ],
            options={
                'db_table': 'maintenance_level',
            },
        ),
        migrations.CreateModel(
            name='Maintenances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Fecha')),
                ('prog_percent', models.CharField(max_length=5, verbose_name='Porcentaje de progreso')),
                ('fk_maintenance_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenances.maintenance_level')),
                ('fk_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.system')),
            ],
            options={
                'db_table': 'maintenances',
            },
        ),
        migrations.CreateModel(
            name='Maintenance_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component.component')),
                ('fk_maintenances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenances.maintenances')),
            ],
            options={
                'db_table': 'maintenance_info',
            },
        ),
    ]
