# Generated by Django 5.2.1 on 2025-07-21 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchase_order', '0001_initial'),
        ('requisition_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionDispatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(verbose_name='Fecha en la que se registra la orden')),
                ('status', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'En Tránsito'), (2, 'Cerrada')], default=0, verbose_name='Estado de la orden')),
                ('type', models.BooleanField(choices=[(True, 'Recepción'), (False, 'Despacho')], default=True, verbose_name='Tipo de Orden: Recepción o Despacho')),
            ],
            options={
                'db_table': 'reception_dispatch_order',
            },
        ),
        migrations.CreateModel(
            name='ReceptionDispatchOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=255, null=True, verbose_name='Observación')),
                ('fk_destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_receptions', to='inventory.location', verbose_name='Locación de Destino')),
                ('fk_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='Inventario')),
                ('fk_origin_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.location')),
                ('fk_purchase_order_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_order.purchaseorderdetails', verbose_name='Detalles de Orden de Compra')),
                ('fk_reception_dispatch_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch_order.receptiondispatchorder', verbose_name='Orden de Recepción/Despacho')),
                ('fk_requisition_order_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requisition_order.requisitionorderdetails', verbose_name='Detalles de Orden de Requisición')),
            ],
            options={
                'db_table': 'reception_dispatch_order_details',
            },
        ),
    ]
