# Generated by Django 4.2 on 2026-04-29 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la tarea')),
                ('task_type', models.CharField(choices=[('inspection', 'Inspección'), ('maintenance', 'Mantenimiento'), ('overhaul', 'Overhaul'), ('calibration', 'Calibración')], default='maintenance', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(verbose_name='Fecha límite')),
                ('estimated_hours', models.FloatField(default=0, verbose_name='Horas estimadas')),
                ('actual_hours', models.FloatField(default=0, verbose_name='Horas realizadas')),
                ('completion_percentage', models.IntegerField(default=0, verbose_name='% Completado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='system.system')),
            ],
            options={
                'verbose_name': 'Tarea de aeronave',
                'verbose_name_plural': 'Tareas de aeronaves',
                'db_table': 'aircraft_task',
                'ordering': ['due_date'],
            },
        ),
    ]
