# Generated by Django 4.2 on 2026-04-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del evento')),
                ('event_type', models.CharField(choices=[('maintenance', 'Mantenimiento'), ('inspection', 'Inspección'), ('overhaul', 'Overhaul')], default='maintenance', max_length=20)),
                ('date', models.DateField(verbose_name='Fecha del evento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='system.system')),
            ],
            options={
                'verbose_name': 'Evento de aeronave',
                'verbose_name_plural': 'Eventos de aeronaves',
                'db_table': 'aircraft_event',
                'ordering': ['date'],
            },
        ),
    ]
