# Generated by Django 4.2 on 2026-04-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('home', '0002_aircraftevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('estructural', 'Estructural'), ('propulsion', 'Propulsión'), ('control_vuelo', 'Control de Vuelo'), ('avionica', 'Aviónica')], max_length=50, verbose_name='Subsistema')),
                ('percentage', models.IntegerField(default=85, verbose_name='Porcentaje de salud')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsystems', to='system.system')),
            ],
            options={
                'verbose_name': 'Subsistema de aeronave',
                'verbose_name_plural': 'Subsistemas de aeronaves',
                'db_table': 'aircraft_subsystem',
                'unique_together': {('aircraft', 'name')},
            },
        ),
    ]
