# Generated by Django 4.2 on 2026-05-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('home', '0003_subsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaMaestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('numero_parte', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('consumible', 'Consumible'), ('reparable', 'Reparable'), ('herramienta_comun', 'Herramienta Común'), ('herramienta_especial', 'Herramienta Especial'), ('equipo_verificacion', 'Equipo de Verificación'), ('equipo_calibracion', 'Equipo de Calibración')], max_length=30)),
                ('unidad_medida', models.CharField(default='unidad', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('tiempo_entrega_dias', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'lista_maestra',
            },
        ),
        migrations.CreateModel(
            name='ProgramaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('horas', 'Por Horas de Vuelo'), ('calendario', 'Por Calendario'), ('ciclos', 'Por Ciclos'), ('condicional', 'Por Condición')], max_length=20)),
                ('intervalo_horas', models.IntegerField(default=0)),
                ('intervalo_dias', models.IntegerField(default=0)),
                ('intervalo_ciclos', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('horas_estimadas', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'programa_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='SubsystemStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.IntegerField(default=1)),
                ('orden', models.IntegerField(default=0)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.subsystemstructure')),
            ],
            options={
                'db_table': 'subsystem_structure',
                'ordering': ['nivel', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('en_compra', 'En Compra'), ('recibido', 'Recibido'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('aeronave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.system')),
            ],
            options={
                'db_table': 'requerimiento',
            },
        ),
        migrations.CreateModel(
            name='ProgramaMantenimientoAeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_realizacion', models.DateField(blank=True, null=True)),
                ('ultimas_horas', models.IntegerField(default=0)),
                ('proxima_realizacion', models.DateField(blank=True, null=True)),
                ('proximas_horas', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_mantenimiento', to='system.system')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.programamantenimiento')),
            ],
            options={
                'db_table': 'programa_mantenimiento_aeronave',
                'unique_together': {('aeronave', 'programa')},
            },
        ),
        migrations.CreateModel(
            name='InventarioStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(default='Almacén Principal', max_length=100)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('cantidad_minima', models.IntegerField(default=0)),
                ('cantidad_maxima', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='home.listamaestra')),
            ],
            options={
                'db_table': 'inventario_stock',
            },
        ),
        migrations.CreateModel(
            name='InspeccionRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField()),
                ('horas_acumuladas', models.IntegerField()),
                ('horas_productivas', models.IntegerField(default=0)),
                ('tiempo_impartido', models.DurationField(blank=True, null=True)),
                ('cumplimiento_porcentaje', models.IntegerField(default=100)),
                ('observaciones', models.TextField(blank=True)),
                ('tecnico_responsable', models.CharField(blank=True, max_length=100)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='system.system')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.programamantenimientoaeronave')),
            ],
            options={
                'db_table': 'inspeccion_realizada',
                'ordering': ['-fecha_realizacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('cantidad_aprobada', models.IntegerField(default=0)),
                ('cantidad_recibida', models.IntegerField(default=0)),
                ('observacion', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.listamaestra')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='home.requerimiento')),
            ],
            options={
                'db_table': 'detalle_requerimiento',
            },
        ),
        migrations.CreateModel(
            name='ComponenteAeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('numero_parte', models.CharField(max_length=100)),
                ('horas_acumuladas', models.IntegerField(default=0)),
                ('ciclos_acumulados', models.IntegerField(default=0)),
                ('vida_util_horas', models.IntegerField(default=0)),
                ('vida_util_ciclos', models.IntegerField(default=0)),
                ('ultimo_cambio', models.DateField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='system.system')),
                ('subsistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subsystemstructure')),
            ],
            options={
                'db_table': 'componente_aeronave',
                'ordering': ['subsistema__nivel', 'codigo'],
                'unique_together': {('aeronave', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='MaterialRequerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('frecuencia_horas', models.IntegerField(default=0)),
                ('observacion', models.TextField(blank=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_requeridos', to='home.componenteaeronave')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.listamaestra')),
            ],
            options={
                'db_table': 'material_requerido',
                'unique_together': {('componente', 'material')},
            },
        ),
    ]
