# Generated by Django 4.2 on 2026-05-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_listamaestra_programamantenimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallerequerimiento',
            name='material',
        ),
        migrations.RemoveField(
            model_name='detallerequerimiento',
            name='requerimiento',
        ),
        migrations.RemoveField(
            model_name='inspeccionrealizada',
            name='aeronave',
        ),
        migrations.RemoveField(
            model_name='inspeccionrealizada',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='inventariostock',
            name='material',
        ),
        migrations.AlterUniqueTogether(
            name='materialrequerido',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='materialrequerido',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='materialrequerido',
            name='material',
        ),
        migrations.AlterUniqueTogether(
            name='programamantenimientoaeronave',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='programamantenimientoaeronave',
            name='aeronave',
        ),
        migrations.RemoveField(
            model_name='programamantenimientoaeronave',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='requerimiento',
            name='aeronave',
        ),
        migrations.RemoveField(
            model_name='subsystemstructure',
            name='padre',
        ),
        migrations.DeleteModel(
            name='ComponenteAeronave',
        ),
        migrations.DeleteModel(
            name='DetalleRequerimiento',
        ),
        migrations.DeleteModel(
            name='InspeccionRealizada',
        ),
        migrations.DeleteModel(
            name='InventarioStock',
        ),
        migrations.DeleteModel(
            name='ListaMaestra',
        ),
        migrations.DeleteModel(
            name='MaterialRequerido',
        ),
        migrations.DeleteModel(
            name='ProgramaMantenimiento',
        ),
        migrations.DeleteModel(
            name='ProgramaMantenimientoAeronave',
        ),
        migrations.DeleteModel(
            name='Requerimiento',
        ),
        migrations.DeleteModel(
            name='SubsystemStructure',
        ),
    ]
