# Generated by Django 5.2.1 on 2025-07-21 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(verbose_name='Fecha en la que se registra la orden')),
                ('status', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'En Tránsito'), (2, 'Cerrada')], default=0, verbose_name='Estado de la orden')),
            ],
            options={
                'db_table': 'requisition_order',
            },
        ),
        migrations.CreateModel(
            name='RequisitionOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Fecha a partir de la que se espera recibir')),
                ('end_date', models.DateTimeField(verbose_name='Fecha hasta la que se espera recibir')),
                ('minimum_quantity', models.IntegerField(verbose_name='Cantidad mínima de material a recibir')),
                ('estimated_arrival', models.DateTimeField(verbose_name='Fecha en la que se estima recibir')),
                ('observation', models.CharField(default='Sin observación', max_length=255, verbose_name='Observación sólo si la orden se cierra sin recibir la cantidad mínima o cumplir la vigencia')),
                ('fk_destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location', verbose_name='Locación de Destino')),
                ('fk_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='Inventario')),
                ('fk_requisition_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisition_order.requisitionorder', verbose_name='Orden de Requisición')),
            ],
            options={
                'db_table': 'requisition_order_details',
            },
        ),
    ]
